runtime: python312
entrypoint: gunicorn -b :$PORT app:app

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  GAE_ENV: 'standard'
  GOOGLE_CLOUD_PROJECT: 'sentetik'
  CLOUD_STORAGE_BUCKET: 'sentetik_research'

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always 